'use strict';

module.exports = {
	errornotifications: { version: 1.0 },
	extremeforecast: { version: 1.0 },
	extremeswwc: { version: 1.2 },
	forestfireindex: { version: 1.1 },
	geosatellite: { version: 1.3 },
	gribfiles: { version: 1.0 },
	icemap: { version: 1.0 },
	locationforecast: { version: 1.9, format: 'xml' },
	locationforecastlts: { version: 1.2, format: 'xml' },
	metfare: { version: 0.1 },
	metgm: { version: 1.0 },
	mountaineasterobservations: { version: 1.0 },
	oceanforecast: { version: 0.9 },
	polarsatellite: { version: 1.1 },
	probabilityforecast: { version: 1.1 },
	radar: { version: 1.5 },
	seaapproachforecast: { version: 1.0 },
	seasonforecast: { version: 1.0 },
	subjectiveforecast: { version: 1.0 },
	sunrise: { version: 1.1 },
	temperatureverification: { version: 1.0 },
	textforecast: { version: 1.6 },
	textlocation: { version: 1.0 },
	tidalwater: { version: 1.1 },
	trondheimsleia: { version: 1.0 },
	turbulence: { version: 1.0 },
	uvforecast: { version: 1.0 },
	weatherformetnosite: { version: 1.0 },
	weathericon: { version: 1.1 }
};
